steps:
  - label: ":hammer: Build1"
    branches: "main"
    command: "scripts/build.sh"
    key: build1

  - label: ":test_tube: Test1"
    command: "scripts/test.sh"
    key: test
    depends_on: build

  - label: ":rocket: Deploy1"
    command: "scripts/deploy.sh"
    key: deploy
    depends_on: test
