steps:
  - label: ":hammer: Build1"
    branches: "main"
    command: "scripts/build.sh"
    key: build1

  - label: ":test_tube: Test1"
    command: "scripts/test.sh"
    key: test1
    depends_on: build1

  - label: ":rocket: Deploy1"
    command: "scripts/deploy.sh"
    key: deploy1
    depends_on: test1
