steps:
  - label: ":hammer: Build2"
    command: "scripts/build.sh"
    key: build2

  - label: ":test_tube: Test2"
    command: "scripts/test.sh"
    key: test2
    depends_on: build2

  - label: ":rocket: Deploy2"
    command: "scripts/deploy.sh"
    key: deploy2
    depends_on: test2
